train:
  name: UGPCLTrainer
  kwargs:
    criterions:
      - name: DiceLoss_
        kwargs: { weight: 0.5 ,n_classes: 4, class_weight: [ 0.0, 1.0, 1.0, 1.0 ] }
      - name: CrossEntropyLoss_
        kwargs: { weight: 0.5 }
    metrics: # metrics config list
      - name: Dice
        kwargs:
          name: Dice
          class_indexs: [ 0, 1, 2, 3 ]
          class_names: [ bg, c1, c2, c3 ]
      - name: Jaccard
        kwargs:
          name: Jaccard
          class_indexs: [ 0, 1, 2, 3 ]
          class_names: [ bg, c1, c2, c3 ]
    labeled_bs: 8
    consistency: 0.1
    consistency_rampup: 60.0
    contrast_weight: 0.1
    temperature: 0.07
    base_temperature: 0.07
    memory: true
    max_samples: 1024
    max_views: 1
    memory_size: 2000
    pixel_update_freq: 10
    pixel_classes: 4
    max_iter: 6000
    eval_interval: 1000
    save_image_interval: 50
    save_ckpt_interval: 1000

optimizer:
  name: SGD
  kwargs:
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.9

scheduler:
  name: PolyLR
  kwargs:
    max_iters: 6000
    power: 0.9
    last_epoch: -1
    min_lr: 0.0001

logger:
  log_file: True
  tensorboard: True
